// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: admin/admin_leases.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ServerId      string                 `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "pending" | "bound" | "error"
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	BoundAt       string                 `protobuf:"bytes,7,opt,name=bound_at,json=boundAt,proto3" json:"bound_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseProto) Reset() {
	*x = LeaseProto{}
	mi := &file_admin_admin_leases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseProto) ProtoMessage() {}

func (x *LeaseProto) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_leases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseProto.ProtoReflect.Descriptor instead.
func (*LeaseProto) Descriptor() ([]byte, []int) {
	return file_admin_admin_leases_proto_rawDescGZIP(), []int{0}
}

func (x *LeaseProto) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseProto) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *LeaseProto) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *LeaseProto) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *LeaseProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LeaseProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LeaseProto) GetBoundAt() string {
	if x != nil {
		return x.BoundAt
	}
	return ""
}

func (x *LeaseProto) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ListLeasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leases        []*LeaseProto          `protobuf:"bytes,1,rep,name=leases,proto3" json:"leases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeasesResponse) Reset() {
	*x = ListLeasesResponse{}
	mi := &file_admin_admin_leases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeasesResponse) ProtoMessage() {}

func (x *ListLeasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_leases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeasesResponse.ProtoReflect.Descriptor instead.
func (*ListLeasesResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_leases_proto_rawDescGZIP(), []int{1}
}

func (x *ListLeasesResponse) GetLeases() []*LeaseProto {
	if x != nil {
		return x.Leases
	}
	return nil
}

type GetLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaseRequest) Reset() {
	*x = GetLeaseRequest{}
	mi := &file_admin_admin_leases_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaseRequest) ProtoMessage() {}

func (x *GetLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_leases_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaseRequest.ProtoReflect.Descriptor instead.
func (*GetLeaseRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_leases_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type RevokeLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeLeaseRequest) Reset() {
	*x = RevokeLeaseRequest{}
	mi := &file_admin_admin_leases_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeLeaseRequest) ProtoMessage() {}

func (x *RevokeLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_leases_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeLeaseRequest.ProtoReflect.Descriptor instead.
func (*RevokeLeaseRequest) Descriptor() ([]byte, []int) {
	return file_admin_admin_leases_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

var File_admin_admin_leases_proto protoreflect.FileDescriptor

const file_admin_admin_leases_proto_rawDesc = "" +
	"\n" +
	"\x18admin/admin_leases.proto\x12\x05admin\x1a\x12admin/common.proto\"\xe8\x01\n" +
	"\n" +
	"LeaseProto\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1b\n" +
	"\tserver_id\x18\x04 \x01(\tR\bserverId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x19\n" +
	"\bbound_at\x18\a \x01(\tR\aboundAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\"?\n" +
	"\x12ListLeasesResponse\x12)\n" +
	"\x06leases\x18\x01 \x03(\v2\x11.admin.LeaseProtoR\x06leases\",\n" +
	"\x0fGetLeaseRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"/\n" +
	"\x12RevokeLeaseRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId2\xb0\x01\n" +
	"\x12AdminLeasesService\x121\n" +
	"\x04List\x12\f.admin.Empty\x1a\x19.admin.ListLeasesResponse\"\x00\x122\n" +
	"\x03Get\x12\x16.admin.GetLeaseRequest\x1a\x11.admin.LeaseProto\"\x00\x123\n" +
	"\x06Revoke\x12\x19.admin.RevokeLeaseRequest\x1a\f.admin.Empty\"\x00BCZAgithub.com/ambientlabscomputing/hyphae/internal/proto/admin;adminb\x06proto3"

var (
	file_admin_admin_leases_proto_rawDescOnce sync.Once
	file_admin_admin_leases_proto_rawDescData []byte
)

func file_admin_admin_leases_proto_rawDescGZIP() []byte {
	file_admin_admin_leases_proto_rawDescOnce.Do(func() {
		file_admin_admin_leases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_admin_leases_proto_rawDesc), len(file_admin_admin_leases_proto_rawDesc)))
	})
	return file_admin_admin_leases_proto_rawDescData
}

var file_admin_admin_leases_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_admin_admin_leases_proto_goTypes = []any{
	(*LeaseProto)(nil),         // 0: admin.LeaseProto
	(*ListLeasesResponse)(nil), // 1: admin.ListLeasesResponse
	(*GetLeaseRequest)(nil),    // 2: admin.GetLeaseRequest
	(*RevokeLeaseRequest)(nil), // 3: admin.RevokeLeaseRequest
	(*Empty)(nil),              // 4: admin.Empty
}
var file_admin_admin_leases_proto_depIdxs = []int32{
	0, // 0: admin.ListLeasesResponse.leases:type_name -> admin.LeaseProto
	4, // 1: admin.AdminLeasesService.List:input_type -> admin.Empty
	2, // 2: admin.AdminLeasesService.Get:input_type -> admin.GetLeaseRequest
	3, // 3: admin.AdminLeasesService.Revoke:input_type -> admin.RevokeLeaseRequest
	1, // 4: admin.AdminLeasesService.List:output_type -> admin.ListLeasesResponse
	0, // 5: admin.AdminLeasesService.Get:output_type -> admin.LeaseProto
	4, // 6: admin.AdminLeasesService.Revoke:output_type -> admin.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admin_admin_leases_proto_init() }
func file_admin_admin_leases_proto_init() {
	if File_admin_admin_leases_proto != nil {
		return
	}
	file_admin_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_admin_leases_proto_rawDesc), len(file_admin_admin_leases_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_admin_leases_proto_goTypes,
		DependencyIndexes: file_admin_admin_leases_proto_depIdxs,
		MessageInfos:      file_admin_admin_leases_proto_msgTypes,
	}.Build()
	File_admin_admin_leases_proto = out.File
	file_admin_admin_leases_proto_goTypes = nil
	file_admin_admin_leases_proto_depIdxs = nil
}
