// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: admin/admin_leases.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminLeasesService_List_FullMethodName   = "/admin.AdminLeasesService/List"
	AdminLeasesService_Get_FullMethodName    = "/admin.AdminLeasesService/Get"
	AdminLeasesService_Revoke_FullMethodName = "/admin.AdminLeasesService/Revoke"
)

// AdminLeasesServiceClient is the client API for AdminLeasesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminLeasesService exposes lease management over the admin socket.
type AdminLeasesServiceClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListLeasesResponse, error)
	Get(ctx context.Context, in *GetLeaseRequest, opts ...grpc.CallOption) (*LeaseProto, error)
	Revoke(ctx context.Context, in *RevokeLeaseRequest, opts ...grpc.CallOption) (*Empty, error)
}

type adminLeasesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminLeasesServiceClient(cc grpc.ClientConnInterface) AdminLeasesServiceClient {
	return &adminLeasesServiceClient{cc}
}

func (c *adminLeasesServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListLeasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeasesResponse)
	err := c.cc.Invoke(ctx, AdminLeasesService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminLeasesServiceClient) Get(ctx context.Context, in *GetLeaseRequest, opts ...grpc.CallOption) (*LeaseProto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseProto)
	err := c.cc.Invoke(ctx, AdminLeasesService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminLeasesServiceClient) Revoke(ctx context.Context, in *RevokeLeaseRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminLeasesService_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminLeasesServiceServer is the server API for AdminLeasesService service.
// All implementations must embed UnimplementedAdminLeasesServiceServer
// for forward compatibility.
//
// AdminLeasesService exposes lease management over the admin socket.
type AdminLeasesServiceServer interface {
	List(context.Context, *Empty) (*ListLeasesResponse, error)
	Get(context.Context, *GetLeaseRequest) (*LeaseProto, error)
	Revoke(context.Context, *RevokeLeaseRequest) (*Empty, error)
	mustEmbedUnimplementedAdminLeasesServiceServer()
}

// UnimplementedAdminLeasesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminLeasesServiceServer struct{}

func (UnimplementedAdminLeasesServiceServer) List(context.Context, *Empty) (*ListLeasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAdminLeasesServiceServer) Get(context.Context, *GetLeaseRequest) (*LeaseProto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAdminLeasesServiceServer) Revoke(context.Context, *RevokeLeaseRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedAdminLeasesServiceServer) mustEmbedUnimplementedAdminLeasesServiceServer() {}
func (UnimplementedAdminLeasesServiceServer) testEmbeddedByValue()                            {}

// UnsafeAdminLeasesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminLeasesServiceServer will
// result in compilation errors.
type UnsafeAdminLeasesServiceServer interface {
	mustEmbedUnimplementedAdminLeasesServiceServer()
}

func RegisterAdminLeasesServiceServer(s grpc.ServiceRegistrar, srv AdminLeasesServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminLeasesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminLeasesService_ServiceDesc, srv)
}

func _AdminLeasesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminLeasesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminLeasesService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminLeasesServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminLeasesService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminLeasesServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminLeasesService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminLeasesServiceServer).Get(ctx, req.(*GetLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminLeasesService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminLeasesServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminLeasesService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminLeasesServiceServer).Revoke(ctx, req.(*RevokeLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminLeasesService_ServiceDesc is the grpc.ServiceDesc for AdminLeasesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminLeasesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminLeasesService",
	HandlerType: (*AdminLeasesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AdminLeasesService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AdminLeasesService_Get_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _AdminLeasesService_Revoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/admin_leases.proto",
}
