// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: admin/admin_connections.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminConnectionsService_List_FullMethodName = "/admin.AdminConnectionsService/List"
)

// AdminConnectionsServiceClient is the client API for AdminConnectionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminConnectionsService exposes live tunnel connection info over the admin socket.
type AdminConnectionsServiceClient interface {
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListConnectionsResponse, error)
}

type adminConnectionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminConnectionsServiceClient(cc grpc.ClientConnInterface) AdminConnectionsServiceClient {
	return &adminConnectionsServiceClient{cc}
}

func (c *adminConnectionsServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectionsResponse)
	err := c.cc.Invoke(ctx, AdminConnectionsService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminConnectionsServiceServer is the server API for AdminConnectionsService service.
// All implementations must embed UnimplementedAdminConnectionsServiceServer
// for forward compatibility.
//
// AdminConnectionsService exposes live tunnel connection info over the admin socket.
type AdminConnectionsServiceServer interface {
	List(context.Context, *Empty) (*ListConnectionsResponse, error)
	mustEmbedUnimplementedAdminConnectionsServiceServer()
}

// UnimplementedAdminConnectionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminConnectionsServiceServer struct{}

func (UnimplementedAdminConnectionsServiceServer) List(context.Context, *Empty) (*ListConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAdminConnectionsServiceServer) mustEmbedUnimplementedAdminConnectionsServiceServer() {
}
func (UnimplementedAdminConnectionsServiceServer) testEmbeddedByValue() {}

// UnsafeAdminConnectionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminConnectionsServiceServer will
// result in compilation errors.
type UnsafeAdminConnectionsServiceServer interface {
	mustEmbedUnimplementedAdminConnectionsServiceServer()
}

func RegisterAdminConnectionsServiceServer(s grpc.ServiceRegistrar, srv AdminConnectionsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminConnectionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminConnectionsService_ServiceDesc, srv)
}

func _AdminConnectionsService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConnectionsServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminConnectionsService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConnectionsServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminConnectionsService_ServiceDesc is the grpc.ServiceDesc for AdminConnectionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminConnectionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminConnectionsService",
	HandlerType: (*AdminConnectionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AdminConnectionsService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/admin_connections.proto",
}
