// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: admin/admin_health.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok" | "degraded"
	LeaseCount      int32                  `protobuf:"varint,2,opt,name=lease_count,json=leaseCount,proto3" json:"lease_count,omitempty"`
	ConnectionCount int32                  `protobuf:"varint,3,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_admin_admin_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetLeaseCount() int32 {
	if x != nil {
		return x.LeaseCount
	}
	return 0
}

func (x *HealthCheckResponse) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

type HealthDetailResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	LeaseCount      int32                  `protobuf:"varint,2,opt,name=lease_count,json=leaseCount,proto3" json:"lease_count,omitempty"`
	ConnectionCount int32                  `protobuf:"varint,3,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	Uptime          string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Version         string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthDetailResponse) Reset() {
	*x = HealthDetailResponse{}
	mi := &file_admin_admin_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthDetailResponse) ProtoMessage() {}

func (x *HealthDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthDetailResponse.ProtoReflect.Descriptor instead.
func (*HealthDetailResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthDetailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthDetailResponse) GetLeaseCount() int32 {
	if x != nil {
		return x.LeaseCount
	}
	return 0
}

func (x *HealthDetailResponse) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *HealthDetailResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *HealthDetailResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_admin_admin_health_proto protoreflect.FileDescriptor

const file_admin_admin_health_proto_rawDesc = "" +
	"\n" +
	"\x18admin/admin_health.proto\x12\x05admin\x1a\x12admin/common.proto\"y\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vlease_count\x18\x02 \x01(\x05R\n" +
	"leaseCount\x12)\n" +
	"\x10connection_count\x18\x03 \x01(\x05R\x0fconnectionCount\"\xac\x01\n" +
	"\x14HealthDetailResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vlease_count\x18\x02 \x01(\x05R\n" +
	"leaseCount\x12)\n" +
	"\x10connection_count\x18\x03 \x01(\x05R\x0fconnectionCount\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion2\x80\x01\n" +
	"\x12AdminHealthService\x123\n" +
	"\x05Check\x12\f.admin.Empty\x1a\x1a.admin.HealthCheckResponse\"\x00\x125\n" +
	"\x06Detail\x12\f.admin.Empty\x1a\x1b.admin.HealthDetailResponse\"\x00BCZAgithub.com/ambientlabscomputing/hyphae/internal/proto/admin;adminb\x06proto3"

var (
	file_admin_admin_health_proto_rawDescOnce sync.Once
	file_admin_admin_health_proto_rawDescData []byte
)

func file_admin_admin_health_proto_rawDescGZIP() []byte {
	file_admin_admin_health_proto_rawDescOnce.Do(func() {
		file_admin_admin_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_admin_health_proto_rawDesc), len(file_admin_admin_health_proto_rawDesc)))
	})
	return file_admin_admin_health_proto_rawDescData
}

var file_admin_admin_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_admin_admin_health_proto_goTypes = []any{
	(*HealthCheckResponse)(nil),  // 0: admin.HealthCheckResponse
	(*HealthDetailResponse)(nil), // 1: admin.HealthDetailResponse
	(*Empty)(nil),                // 2: admin.Empty
}
var file_admin_admin_health_proto_depIdxs = []int32{
	2, // 0: admin.AdminHealthService.Check:input_type -> admin.Empty
	2, // 1: admin.AdminHealthService.Detail:input_type -> admin.Empty
	0, // 2: admin.AdminHealthService.Check:output_type -> admin.HealthCheckResponse
	1, // 3: admin.AdminHealthService.Detail:output_type -> admin.HealthDetailResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_admin_health_proto_init() }
func file_admin_admin_health_proto_init() {
	if File_admin_admin_health_proto != nil {
		return
	}
	file_admin_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_admin_health_proto_rawDesc), len(file_admin_admin_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_admin_health_proto_goTypes,
		DependencyIndexes: file_admin_admin_health_proto_depIdxs,
		MessageInfos:      file_admin_admin_health_proto_msgTypes,
	}.Build()
	File_admin_admin_health_proto = out.File
	file_admin_admin_health_proto_goTypes = nil
	file_admin_admin_health_proto_depIdxs = nil
}
