// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: admin/admin_connections.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        string                 `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,4,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	ConnectedAt   string                 `protobuf:"bytes,5,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionProto) Reset() {
	*x = ConnectionProto{}
	mi := &file_admin_admin_connections_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionProto) ProtoMessage() {}

func (x *ConnectionProto) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_connections_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionProto.ProtoReflect.Descriptor instead.
func (*ConnectionProto) Descriptor() ([]byte, []int) {
	return file_admin_admin_connections_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionProto) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *ConnectionProto) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ConnectionProto) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ConnectionProto) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *ConnectionProto) GetConnectedAt() string {
	if x != nil {
		return x.ConnectedAt
	}
	return ""
}

type ListConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*ConnectionProto     `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectionsResponse) Reset() {
	*x = ListConnectionsResponse{}
	mi := &file_admin_admin_connections_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionsResponse) ProtoMessage() {}

func (x *ListConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_admin_connections_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_admin_admin_connections_proto_rawDescGZIP(), []int{1}
}

func (x *ListConnectionsResponse) GetConnections() []*ConnectionProto {
	if x != nil {
		return x.Connections
	}
	return nil
}

var File_admin_admin_connections_proto protoreflect.FileDescriptor

const file_admin_admin_connections_proto_rawDesc = "" +
	"\n" +
	"\x1dadmin/admin_connections.proto\x12\x05admin\x1a\x12admin/common.proto\"\xa6\x01\n" +
	"\x0fConnectionProto\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\x12\x1f\n" +
	"\vremote_addr\x18\x04 \x01(\tR\n" +
	"remoteAddr\x12!\n" +
	"\fconnected_at\x18\x05 \x01(\tR\vconnectedAt\"S\n" +
	"\x17ListConnectionsResponse\x128\n" +
	"\vconnections\x18\x01 \x03(\v2\x16.admin.ConnectionProtoR\vconnections2Q\n" +
	"\x17AdminConnectionsService\x126\n" +
	"\x04List\x12\f.admin.Empty\x1a\x1e.admin.ListConnectionsResponse\"\x00BCZAgithub.com/ambientlabscomputing/hyphae/internal/proto/admin;adminb\x06proto3"

var (
	file_admin_admin_connections_proto_rawDescOnce sync.Once
	file_admin_admin_connections_proto_rawDescData []byte
)

func file_admin_admin_connections_proto_rawDescGZIP() []byte {
	file_admin_admin_connections_proto_rawDescOnce.Do(func() {
		file_admin_admin_connections_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_admin_connections_proto_rawDesc), len(file_admin_admin_connections_proto_rawDesc)))
	})
	return file_admin_admin_connections_proto_rawDescData
}

var file_admin_admin_connections_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_admin_admin_connections_proto_goTypes = []any{
	(*ConnectionProto)(nil),         // 0: admin.ConnectionProto
	(*ListConnectionsResponse)(nil), // 1: admin.ListConnectionsResponse
	(*Empty)(nil),                   // 2: admin.Empty
}
var file_admin_admin_connections_proto_depIdxs = []int32{
	0, // 0: admin.ListConnectionsResponse.connections:type_name -> admin.ConnectionProto
	2, // 1: admin.AdminConnectionsService.List:input_type -> admin.Empty
	1, // 2: admin.AdminConnectionsService.List:output_type -> admin.ListConnectionsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admin_admin_connections_proto_init() }
func file_admin_admin_connections_proto_init() {
	if File_admin_admin_connections_proto != nil {
		return
	}
	file_admin_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_admin_connections_proto_rawDesc), len(file_admin_admin_connections_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_admin_connections_proto_goTypes,
		DependencyIndexes: file_admin_admin_connections_proto_depIdxs,
		MessageInfos:      file_admin_admin_connections_proto_msgTypes,
	}.Build()
	File_admin_admin_connections_proto = out.File
	file_admin_admin_connections_proto_goTypes = nil
	file_admin_admin_connections_proto_depIdxs = nil
}
